import React from 'react'

import { Container } from 'react-bootstrap'
export default function blogs() {
     return (

          <div>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Est odio veritatis impedit? Quasi aspernatur voluptate, est repellat quos hic necessitatibus, eligendi nulla non aperiam quidem doloribus labore iure iste sapiente dignissimos nisi? Magni adipisci neque eligendi vero, omnis incidunt beatae expedita dolorum sapiente possimus voluptate sed, esse dignissimos impedit itaque molestias necessitatibus autem magnam, fugiat in veritatis dolorem vel nisi. Eaque blanditiis sint quasi. Mollitia dolor blanditiis itaque tempora illum autem eum. Id quis voluptatibus magni tempore, reiciendis ut suscipit ipsam dolor nobis similique molestiae excepturi non optio hic rerum aliquid itaque atque? Nisi explicabo ab maiores perferendis id distinctio odit, harum at quia eaque repudiandae voluptatibus unde, vero doloribus! Enim quos a vel soluta tempore inventore consequatur. Facilis, repellat. Saepe esse amet omnis numquam quos reprehenderit, et cum voluptas quod temporibus quis, necessitatibus hic odit assumenda eveniet alias tenetur ea aspernatur expedita recusandae quasi ut. Facilis blanditiis obcaecati velit ut, consequatur voluptas nihil numquam ea pariatur libero eos aliquid consectetur expedita ex qui ipsa dolor itaque voluptatum tempora unde facere! Praesentium dolore suscipit architecto harum molestiae soluta natus magni, amet reiciendis deserunt accusantium ducimus fuga minima unde, sequi vel minus itaque? Obcaecati nisi fuga amet dolor, quas quasi sint velit expedita distinctio perferendis ab perspiciatis explicabo natus quibusdam culpa sunt repellendus ullam quae aliquam vel? Magnam illum iusto commodi rerum pariatur vitae ad assumenda accusamus doloribus! Tenetur debitis molestias perferendis possimus sit neque excepturi expedita totam vero dignissimos. Fugiat, numquam minima odio voluptatibus cumque excepturi suscipit eos? Blanditiis rem quidem sunt eos itaque doloribus nesciunt nostrum culpa in totam necessitatibus reiciendis deleniti, quisquam veritatis, voluptatum nisi a velit aliquam. Illo eligendi earum officiis voluptatem dolores nisi velit. Harum, commodi accusamus? Quasi accusantium ducimus hic dolores, debitis voluptate minus earum odio harum corrupti vitae minima in mollitia nesciunt, obcaecati sapiente? Suscipit eos quis dolor mollitia iste minus cum velit maxime omnis vel laborum culpa dolores modi temporibus quos at, minima animi ea hic! Aut, magnam non repellendus reiciendis alias eligendi rem eum reprehenderit sed! Adipisci.
          </div>
     )
}
