// importing next component
import Head from 'next/head'
// importing the bootstrap componets 
import { Container } from 'react-bootstrap'
// importing the components desinged by us
import Navbar from '../Components/Navbar'

// main exporting component
export default function Home() {
  //  required fuctions for the component



  return (

    // java script xml returning 
    <div >
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
      </Container>
    </div>
  )
}
